### ISSUE TITLE
Use the format contribution API

### ISSUE THREAD

**Issue by aeschli** [DotJoshJohnson/vscode-xml#1]
Instead of adding a new command, better add yourself as a formatter provider

```
vscode.languages.registerDocumentFormattingEditProvider('xml', ...)
vscode.languages.registerDocumentRangeFormattingEditProvider('xml', ...)
```

You will then get invoked on the built-in Format command.

You can have a look at my css formatter extension:
https://github.com/aeschli/vscode-css-formatter/

**Comment by DotJoshJohnson** [comment]
Good call. I'll study up on that API and tap in. Thank you!

**Comment by DotJoshJohnson** [comment]
Implemented `DocumentFormattingEditProvider` and `DocumentRangeFormattingEditProvider`. The `xmlTools.formatXml` command will remain for backward-compatibility, however, it is simply an alias for the built-in formatting command.
