### ISSUE TITLE
Respect Tab Style

### ISSUE THREAD

**Issue by Rednox** [DotJoshJohnson/vscode-xml#100]
The auto format should respect the "editor.insertSpaces" option.

So if insertSpaces is enabled, the tabs of auto format should be spaces.

**Comment by DotJoshJohnson** [comment]
Hi, @Rednox. XML Tools already supports this functionality. Can you confirm you do not have any other extensions installed that provide XML formatting capabilities?

**Comment by Rednox** [comment]
Hi,
Here is the list of all installed extensions i currently have:

- https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
- https://marketplace.visualstudio.com/items?itemName=austin.code-gnu-global
- https://marketplace.visualstudio.com/items?itemName=twxs.cmake
- https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome
- https://marketplace.visualstudio.com/items?itemName=bbenoist.Doxygen
- https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-FAKE
- https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp
- https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-Paket
- https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
- https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell
- https://marketplace.visualstudio.com/items?itemName=donjayamanne.python
- https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby
- https://marketplace.visualstudio.com/items?itemName=DougFinke.vscode-pandoc
- https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml

I checked the settings and didn't find any obvious conflicts concerning xml formatting.

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.1`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.1). This will be released to the marketplace when `v2.0.0` is out of preview.

**Comment by fhnaseer** [comment]
Its not working for me. Extension adds tabs instead of spaces. Here are my settings,

```
  "files.exclude": {
    "**/bin": true
  },
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "editor.insertSpaces": true,
  "[xml]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
  },
  "xmlTools.enforcePrettySelfClosingTagOnFormat": true,
}
```

I only have two extensions installed (c# and xml tools),

**Comment by FedeAbella** [comment]
This is not working for me either. Disabling this extension prevents any xml formatting, so it is clearly this one that is adding the tabs. Changing indentation style to spaces causes tabs to still be added as indentation.
