### ISSUE TITLE
XML Formatter always appends a new line

### ISSUE THREAD

**Issue by NCC1701M** [DotJoshJohnson/vscode-xml#11]
The XML formatter appends always a new line character at the end of the file even when there is already one. This is needless and in my opinon a bug. Please fix this

**Comment by DotJoshJohnson** [comment]
PR #12

**Comment by DotJoshJohnson** [comment]
Fixed in [v1.0.0](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v1.0.0)
