### ISSUE TITLE
I can't see XML Tree View

### ISSUE THREAD

**Issue by ultranet50** [DotJoshJohnson/vscode-xml#110]
Hi, thanks for the extension.

I can't see the tree view when I list the XML commands in command promt, can you help me?

Thanks and regards, Sam.

**Comment by DotJoshJohnson** [comment]
@ultranet50 - As of v1.9.0, the old tree view that required you to run a command has been replaced by a native tree view in the file explorer menu. It is in a pane titled **XML Document**.

![image](https://user-images.githubusercontent.com/8592596/27504183-72510f8e-5853-11e7-8c26-c24c69208692.png)
