### ISSUE TITLE
VSCode error "Installation appears to be corrupt" after installation of plug-in and reload

### ISSUE THREAD

**Issue by sejal27** [DotJoshJohnson/vscode-xml#114]
After installing this plug-in and reloading vscode, I got this pop-up error : Installation appears to be corrupt
However, I do not see any particular issues with VSCode and plug-in works just fine. I could use formatting and tree view features (they are awesome, btw!). So I am wondering if I need to reinstall VSCode like they have suggested on their FAQ page - https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt

**Comment by DotJoshJohnson** [comment]
I would indeed recommend reinstalling VS Code. This plugin does not apply patches to VS Code, so you should be fine after a reinstall.
