### ISSUE TITLE
Suggestion - Show node/attribute details in treeview

### ISSUE THREAD

**Issue by zspitz** [DotJoshJohnson/vscode-xml#117]
For attributes, you could show the value (in a dimmer color / smaller font); alternatively, the tooltip could show `attribute=value` instead of just the attribute name.
For nodes, you could show the number of child nodes, where greater than 1 (0 child nodes have no expander); and in the tooltip show some part of the XML of the node.

**Comment by brentk7** [comment]
I would definitely second this feature request. Foxe XML editor has a very handy feature which does this - would be great if something like that could be implemented. See link for details:
http://www.firstobject.com/tree-customization-in-xml-editor.htm

**Comment by DotJoshJohnson** [comment]
I can't add tooltips in the tree view - there is not API for that (yet). But I have added child node counts and attribute values. This will be released in `v2.0`.

**Comment by DotJoshJohnson** [comment]
I misspoke! After updating the minimum engine version, I found a tooltip API. I'll look into adding that for a future release.

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.3`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.3).
