### ISSUE TITLE
Maintain Comment Formatting

### ISSUE THREAD

**Issue by ser-drephs** [DotJoshJohnson/vscode-xml#118]
A setting that maintains the comment formatting in XML.

`<!--`
`<Description>`
`   Any description.`
`</Description>`
`<Keyword UUID="fd8e6b13-9865-4d8c-9ecd-5ff08a0cf2e2"/>`
`<Parameters>`
`    <Parameter Name="ParameterName1">The Parameter Name.</Parameter>`
`    <Parameter Name="ParameterName2" PossibleValues="Val1,Val2" DefaultValue="Val1"/>`
`</Parameters>`
`-->`

Becomes:
`<!--`
`<Description>`
`    Any description.`
`</Description><Keyword UUID="fd8e6b13-9865-4d8c-9ecd-5ff08a0cf2e2"/><Parameters><Parameter Name="ParameterName1">The Parameter Name.</Parameter><Parameter Name="ParameterName2" PossibleValues="Val1,Val2" DefaultValue="Val1"/></Parameters>`
`-->`

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.1`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.1). This will be released to the marketplace when `v2.0.0` is out of preview.
