### ISSUE TITLE
Closing tag is moved upwards in an incorrect manner

### ISSUE THREAD

**Issue by andypyrope** [DotJoshJohnson/vscode-xml#120]
When, for example, the following XML is formatted:
```
<Node>
   <Node name="testChild"/>
</Node>
```
It turns into this:
```
<Node>
   <Node name="testChild"/></Node>
```

This is surely not a desired result, because `<Node>` and `</Node>` should be with the same indentation level.

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.1`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.1). This will be released to the marketplace when `v2.0.0` is out of preview.
