### ISSUE TITLE
Sync cursor location to XML Document tree

### ISSUE THREAD

**Issue by dsolovay** [DotJoshJohnson/vscode-xml#121]
Feature request: When the cursor is placed in the text of an XML document, provide a way to locate the currently selected element in the XML Document tree.  The best experience would be similar to the way the File Explorer automatically highlights the current file.  If this cannot be achieved, providing a "Locate node in XML Tree" command and context menu option would be a reasonable fallback approach.

**Comment by johnk1** [comment]
I think this, or a breadcrumb bar based on the cursor position, would be very helpful.

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.3`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.3).

**Comment by mstv** [comment]
Could the XML Document Tree selection be updated on every change of the cursor line? I don't want to need to click a mouse button.

Is there a reason why clicking end tags is not supported?
