### ISSUE TITLE
added XML Tree View for xslt/xsl files

### ISSUE THREAD

**Issue by MarekLew** [DotJoshJohnson/vscode-xml#123]
`XML DOCUMENT` don`t show xslt/xsl files files structure 

Please add to the selection of file extensions that are treated as xml

**Comment by MarekLew** [comment]
At this time I'm using this https://github.com/MarekLew/vscode-xml/commit/aab25d215992643f3673288e5ef3a4afb3750c10

**Comment by DotJoshJohnson** [comment]
You can associate any extension you want to the `xml` language in you workspace preferences. Please see the [VS Code documentation on the topic](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language) for more information.
