### ISSUE TITLE
Option to place element attributes on new lines

### ISSUE THREAD

**Issue by AndyDBell** [DotJoshJohnson/vscode-xml#124]
Hi, 
Very useful extension.  Thank you.

Would it be possible to add an option to place each elements attributes on a new line when formatting?  
i.e. xmlTools.splitAttributesOnFormat
In the case where elements may have a large number of attributes this makes the xml much more readable.

**Comment by lekhnath** [comment]
I would also like to put each attribute in a separate line when formatting so please provide some configuration option to do so

**Comment by nknganda** [comment]
Would also love the same.
For example:

        <report 
            id="report_web_quote"
            string="Web Quotation"
            model="sale.order" 
            report_type="qweb-pdf"
            file="website_quote.report_quotation" 
            name="website_quote.report_quote" 
            menu="False"
        />

**Comment by stefanusz** [comment]
+1 to this suggestion, it will be super helpful to have it! 

Thanks!

**Comment by lekhnath** [comment]
@nknganda using Odoo? :)

**Comment by nknganda** [comment]
Yes @lekhnath. Currently training on it.

**Comment by DotJoshJohnson** [comment]
This feature will be tracked in issue #116.
