### ISSUE TITLE
formatting does not support non-English language tags (XML Formatting)

### ISSUE THREAD

**Issue by sin-raben** [DotJoshJohnson/vscode-xml#125]
formatting does not support non-English language tags (XML Formatting)

example:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<Имя></Имя>
```

**Comment by DotJoshJohnson** [comment]
This will be addressed in v2.x.

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.1`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.1). This will be released to the marketplace when `v2.0.0` is out of preview.
