### ISSUE TITLE
Give option to make side bar optional

### ISSUE THREAD

**Issue by christianflorez** [DotJoshJohnson/vscode-xml#130]
Hello,

Thanks for the great extension. It would be fantastic if there was a small setting that allowed me to disable the side bar that automatically comes with the extension, as of the moment there's no way to opt out of it, taking up screen real estate even when not editing XML documents.

Thanks!

**Comment by TimHiggison** [comment]
You can right click on the XML Document pane header and click Hide from Side Bar to get rid of it. Alternatively you can right click on the Explorer pane header and select XML Document to show and hide the XML Tools side bar.

**Comment by DotJoshJohnson** [comment]
This is fixed as of [`v2.0.0-preview.2`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.2).
