### ISSUE TITLE
Autoformat should keep indentation level

### ISSUE THREAD

**Issue by mojo2012** [DotJoshJohnson/vscode-xml#131]
When I make a text selection like this:
![bildschirmfoto 2017-11-16 um 14 08 11](https://user-images.githubusercontent.com/1330361/32892775-9ca6a2b6-cad7-11e7-9480-150d89c04887.png)

And then I hit cmd-shift-f to invoke auto-format, I get this:
![bildschirmfoto 2017-11-16 um 14 08 43](https://user-images.githubusercontent.com/1330361/32892793-acf8333c-cad7-11e7-8ad3-df76d003b0a0.png)

From the  "n:explorer" element downwards the indentation level is wrong. It seems everythign is aligned on the last closing tag which is on most left column.

Actually It should always use the indentation level based on the whole document, even if just the selection is autoformatted.

**Comment by DotJoshJohnson** [comment]
I will not have time to work on this in the near future. I will accept PRs for this after `v2.0.0` is released.
