### ISSUE TITLE
Reuse code outline panel if installed

### ISSUE THREAD

**Issue by mojo2012** [DotJoshJohnson/vscode-xml#132]
The code outline extension (patrys.vscode-code-outline) provides a "symbol list" for source files.
This is basically the same functionality as this extension provides for xml files.
So why not check, if the other one is installed, and reuse this panel, or at least name it the same way. So that regardless in which file you are, the panel is always named the same way.

**Comment by DotJoshJohnson** [comment]
This would involve adding code symbol support to the XML language. I don't currently have the bandwidth to tackle this, but if anyone is interested in writing up a PR, I'm open to proposals.

**Comment by DotJoshJohnson** [comment]
Closing per my comment in #191.
