### ISSUE TITLE
command 'xmlTools.formatXml' not found

### ISSUE THREAD

**Issue by gorhun** [DotJoshJohnson/vscode-xml#133]
After installing the XML Tools plugin I want to format my XML file. When pressing the CTRL + SHIFT + ALT + B, then I get this error:
command 'xmlTools.formatXml' not found

**Comment by BilliousOz** [comment]
This problem only seems to occur on large XML files, as reported in issue #122.

**Comment by DotJoshJohnson** [comment]
Can you confirm the error references `xmlTools.formatXml` and not `xmlTools.formatAsXml`? The former is not a valid command, but the latter would make this the same issue as #122. I just want to vet this out as a duplicate or confirm it is a separate issue. Thanks!

**Comment by bslezak** [comment]
I just installed the extension and got the same thing. CTRL+ALT+SHIFT+B throws the error, picking the command from CTRL+SHIFT+P works fine. Is it possible the keyboard command got mapped to the wrong command?:
https://www.screencast.com/t/3bXE84fOPTc

**Comment by DotJoshJohnson** [comment]
@bslezak - Nice catch! That is exactly what is going on. I never updated the keybinding when I dropped the old command. I will release a patch this week to address that issue and make sure it gets rolled into the v2 rebuild. Thanks!

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.1`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.1). This will be released to the marketplace when `v2.0.0` is out of preview.
