### ISSUE TITLE
Link to roadmap on home page is broken

### ISSUE THREAD

**Issue by daldr-ntml** [DotJoshJohnson/vscode-xml#135]
On https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml

The link to the roadmap is broken:

https://github.com/DotJoshJohnson/vscode-xml/projects/1

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.1`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.1). This will be released to the marketplace when `v2.0.0` is out of preview.
