### ISSUE TITLE
"Format as XML" cannot handle element text on new line

### ISSUE THREAD

**Issue by Jesperbk** [DotJoshJohnson/vscode-xml#137]
Using the format command on an XML snippet with element text on its own line (or on line with the closing tag) does not yield the expected indentation.
Before:
```
<Tag>
<Tag2>
Text
</Tag2>
</Tag>
```

After:
```
<Tag>
    <Tag2>
Text
</Tag2>
</Tag>
```

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.1`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.1). This will be released to the marketplace when `v2.0.0` is out of preview.
