### ISSUE TITLE
.XLF file extension support

### ISSUE THREAD

**Issue by universonic** [DotJoshJohnson/vscode-xml#140]
Hello. Could you support `.xlf` extension also? or could you add an configuration entry to allow me to  attach my own file extensions to vscode-xml?

**Comment by DotJoshJohnson** [comment]
This can be accomplished by using the [`files.associations` setting in VS Code](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language). The language identifier you want to use is `xml` (the XML language is built into VS Code - this extension doesn't define it).
