### ISSUE TITLE
Unhide XML tree view

### ISSUE THREAD

**Issue by Romeo84095** [DotJoshJohnson/vscode-xml#142]
Hello. I do hide XML tree view. So i can't unhide it back. How can I do that? I can't find any menu items like 'show/hide XML tree view'.

And additionally, how could i move treeView from file pane to somewhere, like tabs pane?

Thanks.

**Comment by dr3adl0rd** [comment]
@Romeo84095 Right click on the "EXPLORER" header above all panels, and select the "XML Document" to un-hide it.
Took me a couple of minutes to find it on vscode forums.
I think we can close this issue as non-issue after all.

**Comment by DotJoshJohnson** [comment]
@Romeo84095 - VS Code does not currently support moving contributed views between areas of the UI.
