### ISSUE TITLE
XML Tools:Executy XQuery does not recognize my XQuery files as XQuery files

### ISSUE THREAD

**Issue by EdgarSchouten** [DotJoshJohnson/vscode-xml#145]
On my C_drive I saved a file test.xqy and a file test.xquery and a file test.xq with the following content
    xquery version "2.0" encoding "utf-8";
    for $i in (1) return $i
It runs correctly with XML Tools:Marklogic Eval XQuery
But it gives an error running XML Tools:Executy XQuery
Error message: "This action can only be performed on an XQuery file."

How can I convince VSCode that those are in fact XQuery files?

**Comment by DotJoshJohnson** [comment]
You can add any extension you want to the `xquery` language in your workspace preferences. Please see the [VS Code documentation on the topic](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language) for more information.
