### ISSUE TITLE
Running Format Document results in error and no formatting performed

### ISSUE THREAD

**Issue by contentfree** [DotJoshJohnson/vscode-xml#146]
Using 1.9.2 with VSC 1.21.0 on macOS, running `Format Document` results in the error "There is no formatter for 'xml'-files installed." and no formatting is performed.

Attempting to run `XML Tools: Format as XML` appears to do nothing. However, it prints an error in the console: "[Extension Host] Cannot execute xmlTools.formatAsXml because there is no active text editor."

That seems quite odd as I'm able to edit the file just fine.

What can I provide to help narrow down the problem?

**Comment by DotJoshJohnson** [comment]
Can you try this in [`v2.0.0-preview.2`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.2)? I do not have a macOS environment to test in at the moment and it is possible this was fixed in the rewrite. The formatter was completely rewritten.

**Comment by DotJoshJohnson** [comment]
Moving to backlog to wrap up 2.0 release.

**Comment by DotJoshJohnson** [comment]
Closing due to lack of response. Please feel free to update the issue if this persists in the current version. Thanks!
