### ISSUE TITLE
Format Document adds unnecessary newlines for self-closing tags

### ISSUE THREAD

**Issue by balljok** [DotJoshJohnson/vscode-xml#147]
"xmlTools.xmlFormatterImplementation": "v2"

When formatting documents containing self-closing tags, an unnecessary newline is added when the self-closing tag is the only element on a line and the line already ends with a newline.

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.3`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.3).
