### ISSUE TITLE
Should not remove newlines from inside XML tag

### ISSUE THREAD

**Issue by abd3** [DotJoshJohnson/vscode-xml#150]
We have some XML whose values contain newlines. The auto-format feature is removing those newlines when saving. This causes us to lose important formatting. Please do not replace newlines inside of XML values.

**Comment by DotJoshJohnson** [comment]
This should be fixed as of [`v2.0.0-preview.2`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.2).
