### ISSUE TITLE
Minify context menu option

### ISSUE THREAD

**Issue by andrewhcmc** [DotJoshJohnson/vscode-xml#151]
Hi,

The Format Document right-click menu option is great, it would be good if the minify command was available as a menu option along side it as well. I often have to format feed files and then want to put them back into single rows again.

**Comment by DotJoshJohnson** [comment]
Released in [`v2.0.0-preview.3`](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v2.0.0-preview.3).
