### ISSUE TITLE
Indenting tags like <br>

### ISSUE THREAD

**Issue by manishrw** [DotJoshJohnson/vscode-xml#156]
Issue Type: <b>Bug</b>

<br> tag is idented one more level. This causes chaos in formatting.

Extension version: 1.9.2
VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz (8 x 3592)|
|Memory (System)|31.76GB (17.51GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DotJoshJohnson** [comment]
Unfortunately, this extension will not reliably format HTML because it isn't valid XML. Self-closing tags are supported (ex. `<br />`), but HTML-style "empty" elements are not.
