### ISSUE TITLE
removeCommentsOnMinify doesn't work

### ISSUE THREAD

**Issue by rthery** [DotJoshJohnson/vscode-xml#157]
When setting removeCommentsOnMinify to true for my workplace, comments such as `<!-- my comment -->` are not removed when using the minify command.

**Comment by DotJoshJohnson** [comment]
@rthery - Could you confirm the version of the extension you are using? Is this the current production release (`v1.9.2`) or the current preview release (`v2.0.0-preview.2`)?

**Comment by rthery** [comment]
Ah yes sorry, it's the current production release from the Marketplace

**Comment by DotJoshJohnson** [comment]
No worries! Are these comments in an unusual place? For example:
```xml
<tagname <!-- comment -->></tagname>
```

or:
```xml
<![CDATA[ <!-- comment --> ]]>
```

If you can provide a sample document that reproduces the issue, that'd be even better.

**Comment by rthery** [comment]
They don't seem out of places, but one of them has an URL, so it may mess up the detection. They are xml files generated by a tool call [TexturePacker](https://www.codeandweb.com/texturepacker). Here's one example not working:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with TexturePacker https://www.codeandweb.com/texturepacker -->
<!-- $TexturePacker:SmartUpdate:fdaf98e35fec1d3fe743ffa82ae73603:2dc847f25158c52f0fa505ee3c6807d9:c3f3af7d3dafac7fb1d98fa28c77df64$ -->
<TextureAtlas imagePath="14.png" width="121" height="98">
    <SubTexture name="3" x="52" y="1" rotated="true" width="24" height="37"/>
    <SubTexture name="5" x="100" y="77" width="12" height="10"/>
    <SubTexture name="7" x="61" y="40" rotated="true" width="9" height="15"/>
    <SubTexture name="9" x="108" y="42" width="8" height="11"/>
</TextureAtlas>
```

Thanks!

**Comment by DotJoshJohnson** [comment]
I've confirmed this works as expected in the "v2" formatter to be released this weekend.
