### ISSUE TITLE
Add support for open drive files (*.xodr)

### ISSUE THREAD

**Issue by ccssmnn** [DotJoshJohnson/vscode-xml#161]
Open drives *.xodr files are *.xml files but with a different ending.

**Comment by RandallFlagg** [comment]
Until the extension has this builtin you can do it manually in the settings:

"files.associations": {
        "*.xodr": "xml",
}

**Comment by DotJoshJohnson** [comment]
Using the file association feature in your VS Code preferences is the preferred way to handle this.
