### ISSUE TITLE
Consider adding when "editorLangId == xml" to all xml specific commands

### ISSUE THREAD

**Issue by Avinm** [DotJoshJohnson/vscode-xml#164]
XML tools currently pollutes the Command Palette even while not viewing/editing xml files. Consider adding language specific filtering of commands.
ref:https://github.com/Avinm/VSCode-Ion-Format-Support/blob/master/package.json#L49-L56

**Comment by DotJoshJohnson** [comment]
Thanks! I didn't even notice that in the docs. I'll add this in the next release.

**Comment by Avinm** [comment]
Unfortunately, "when" attribute is not properly documented, it just happens to be provided as an example @ https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus
