### ISSUE TITLE
Cursor sync : don't automatically open the sidebar

### ISSUE THREAD

**Issue by Otiel** [DotJoshJohnson/vscode-xml#171]
The new "cursor sync" feature (#121) is very neat, but sometimes I want to have my sidebar closed, and I want it to stay closed. Currently, the sidebar is automatically opened when clicking on a node which can be annoying, as shown below:

![xml](https://user-images.githubusercontent.com/3851902/40621483-3123a63e-629d-11e8-8841-606c0d0a6034.gif)

It would be better if the sidebar wouldn't be automatically opened.

**Comment by DotJoshJohnson** [comment]
As long as there is an API that would allow me to determine if the sidebar is collapsed or not, I can easily add this. I'm not sure if such an API exists, though. I'll do some research on this and add it in the next release if it is something the extensibility API will support. Thanks!

**Comment by DotJoshJohnson** [comment]
Just as a note for reference, if I cannot use the API to determine if the sidebar is open/closed, the next release will disable the cursor sync by default until such an API is made available.
