### ISSUE TITLE
Side bar opens automatically

### ISSUE THREAD

**Issue by Morgy93** [DotJoshJohnson/vscode-xml#176]
**Description**
If I edit some xml file the side bar opens up automatically.
Even though I set `xmlTools.enableXmlTreeView` to `false`

**Screenshots**
![xml](https://user-images.githubusercontent.com/7961978/40646728-5e7d3e50-632a-11e8-8915-ca39e3af7447.gif)

**Extension Version**
2.1.1

**VS Code Version**
1.23.1

**Operating System**
Windows 10 Pro 1803 (17134.81) x64

**Comment by DotJoshJohnson** [comment]
This is caused by the "cursor sync" feature. You should be able to correct by setting `xmlTools.enableXmlTreeViewCursorSync` to `false`. A permanent fix is being tracked in issue #171.

**Comment by Morgy93** [comment]
Yes, it works! Thanks!

Closed in favor of #171

**Comment by Morgy93** [comment]
Yes, it works! Thanks!

Closed in favor of #171
