### ISSUE TITLE
XML formatter is sensitive to single quotes

### ISSUE THREAD

**Issue by bersbersbers** [DotJoshJohnson/vscode-xml#177]
#### Description
Indentation is messed up with this example file:

```
<root>
  <element attr='1'>
  <element attr='2'>
</root>
```

This is formatted as 
```
<root>
  <element attr='1'>
<element attr='2'>
</root>
```

#### Formatter Implementation
v2

#### XML Tools Version
2.1.1

#### VS Code Version
1.23.1
#### Operating System
Win 10

**Comment by DotJoshJohnson** [comment]
These changes will support single-quoted attribute values, but keep in mind, the sample XML in this issue will likely still have issues as it is not valid XML. Self-closing tags must end with "/>" unlike HTML.

**Comment by bersbersbers** [comment]
You are right, I must have introduced these errors in minimizing my example code - thanks for pointing them out. Thanks for the quick fix as well :)
