### ISSUE TITLE
Classic formatter adds new line at beginning of file

### ISSUE THREAD

**Issue by KWeaver87** [DotJoshJohnson/vscode-xml#179]
#### Description
The classic formatter adds a blank new line at the beginning of the file.

#### Formatter Implementation
classic

#### XML Tools Version
2.1.1

#### VS Code Version
1.23.0

#### Operating System
Windows 10 Build 1709

**Comment by DotJoshJohnson** [comment]
Thanks for the report! I do not intend to maintain the classic formatter moving forward. It has been included in v2.x as a "rollback" option for anyone broken by the v2 formatter.
