### ISSUE TITLE
Spaces between tag and first attribute won't be formatted

### ISSUE THREAD

**Issue by davity** [DotJoshJohnson/vscode-xml#18]
Before

``` xml
<node    attr="none"    attr2="lots"    attr3="less"    >    </node>
```

After

``` xml
<node    attr="none" attr2="lots" attr3="less"    ></node>
```

Spaces between `node` and `attr1` should be merged into only one space.
Also, spaces before the closing `>` aren't treated.

Attributes `attr1`, `attr2` and `attr3` were spaced correctly with each other.

**Comment by DotJoshJohnson** [comment]
Thanks for reporting! This has been released in [version 1.3.2](https://github.com/DotJoshJohnson/vscode-xml/releases/tag/v1.3.2).
