### ISSUE TITLE
XML navigator opens when side bar is disabled

### ISSUE THREAD

**Issue by perlun** [DotJoshJohnson/vscode-xml#181]
Issue Type: <b>Bug</b>

When editing an XML file (e.g. a `.csproj` file), the XML Document highlights the active file in the side bar. This is fine and all, but: if you _disable_ the side bar and click on a node in an XML file, the side bar is made visible again and the XML document tree highlights the node you clicked on. Very bad user experience, since this means that it's actually impossible to disable the side bar and click around in an XML document:

![image](https://user-images.githubusercontent.com/630613/40661607-e8bdc17a-635c-11e8-91e0-cf45b286467d.png)

What I've tried so far:

- Right click the side bar, disable the XML Document. Doesn't help, same problem.
- Disable the XML extension - this makes the problem go away.

VS Code version: Code - Insiders 1.24.0-insider (bfd155e6039f64d2795c6b514a029ebd01a33527, 2018-05-29T06:13:09.810Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 5, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_11139743|
|Screen Reader|no|
|VM|17%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
addlocalnetreferences|Raf|0.0.3
vscode-wakatime|Wak|1.2.2
solargraph|cas|0.17.4
vscode-eslint|dba|1.4.10
xml|Dot|2.1.1
gitlens|eam|8.3.2
tslint|eg2|1.0.30
Ionide-fsharp|Ion|3.20.8
vscode-nuget-package-manager|jmr|1.1.6
markdown-converter|man|0.0.11
dotenv|mik|1.0.1
mssql|ms-|1.3.1
cpptools|ms-|0.17.3
csharp|ms-|1.15.2
debugger-for-chrome|msj|4.4.3
vscode-docker|Pet|0.0.27
Ruby|reb|0.18.0
java|red|0.25.0
vscode-yaml|red|0.0.12
vscode-icons|rob|7.23.0
rust|rus|0.4.4
vscode-nginx|sha|0.5.0
vscode-spotify|shy|2.4.0
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
vscode-gfm-preview|tom|0.1.2
vscode-java-debug|vsc|0.9.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.6.1
vscode-maven|vsc|0.8.0

(7 theme extensions excluded)

</details>

**Comment by DotJoshJohnson** [comment]
This will be fixed in the next release. For now, setting `xmlTools.enableXmlTreeViewCursorSync` to `false` will fix the issue.

**Comment by DotJoshJohnson** [comment]
Please follow #171 for further updates.

**Comment by perlun** [comment]
Thanks @DotJoshJohnson for a super-fast reply and status update - sorry for the noise! (I did skim through the issues but apparently not diligently enough. 😢)

**Comment by DotJoshJohnson** [comment]
No worries!
