### ISSUE TITLE
Attribute values containing special chars shouldn't be touched.

### ISSUE THREAD

**Issue by mschleeweiss** [DotJoshJohnson/vscode-xml#189]
#### Description
When formatting XML where an attribute has a value that contains special chars (like single quotes) they also become formatted:

Input:

    <!DOCTYPE xml>
    <core:FragmentDefinition xmlns="sap.m" 
        xmlns:core="sap.ui.core">
            <Text text="{parts: ['i18n>dialog.countdown.text','view>/Countdown'],formatter: 'jQuery.sap.formatMessage'}" />
        </Dialog>
    </core:FragmentDefinition>

Format once:

    <!DOCTYPE xml>
    <core:FragmentDefinition xmlns="sap.m" 
        xmlns:core="sap.ui.core">

        <Text text="{parts: ['
            i18n>dialog.countdown.text','
            view>/Countdown'],formatter: '
            jQuery.sap.formatMessage'}" />

    </core:FragmentDefinition>

Format twice:

    <!DOCTYPE xml>
    <core:FragmentDefinition xmlns="sap.m" 
        xmlns:core="sap.ui.core">

        <Text text="{parts: ['
        
            i18n>dialog.countdown.text','
        
            view>/Countdown'],formatter: '
        
            jQuery.sap.formatMessage'}" />

    </core:FragmentDefinition>

The more you format it, the more newlines will be added in the `text` attribute. Imo the input shouldn't be formatted further, as it's already intended correctly and every attribute is on its own line.

#### Formatter Implementation
Which XML Formatter implementation are you using (the value of your `xmlTools.xmlFormatterImplementation` setting).

`v2`

#### XML Tools Version
What version of XML Tools are you using?

2.2.0

#### VS Code Version
What version of VS Code are you using?

1.23.1

#### Operating System
What OS (and version) are you using?

Windows 10

**Comment by DotJoshJohnson** [comment]
This was fixed in issue #187, but I've added this sample XML as a test case to ensure things like braces don't end up breaking in the future as I don't personally run into it very often.
