### ISSUE TITLE
Add encoding detection

### ISSUE THREAD

**Issue by perseus-me** [DotJoshJohnson/vscode-xml#190]
**Description**
Add encoding detection. Read first line from xml file, and reopen file with correct encoding. VS Code usually open files in `utf-8` encoding.

**Current Workarounds**
Reopen file with correct encoding manually.  `cmd + shift + p` -> `change file encoding` -> `reopen with encoding`

**Comment by TheAifam5** [comment]
I think that's a problem with VSCode, not with that project.
The file opening and encoding detection is inside of VSCode.

**Comment by perseus-me** [comment]
Yep, you're right! I found issue in vscode repo.

https://github.com/Microsoft/vscode/issues/36230
