### ISSUE TITLE
XSL formatting does not work

### ISSUE THREAD

**Issue by ihateids** [DotJoshJohnson/vscode-xml#192]
After one of the recent updates, it is not possible to format XSL document anymore. The formatting option has also disappeared from context menu for XSL files. The formatting of XML document works fine.

Thank you
M

**Comment by amrtn** [comment]
I've been using the_"XML Tools: Format as XML"_  tool at the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) to format XSL files.

**Comment by DotJoshJohnson** [comment]
You can use the "XML Tools: Format as XML" command as @amrtn mentioned to format any file. You can also treat specific file types as XML by using the [`files.associations` setting in VS Code](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language). The language identifier you want to use is `xml` (the XML language is built into VS Code - this extension doesn't define it). I will likely add "native" support for well-known extensions like XSL in a future update.

**Comment by ihateids** [comment]
Thank you guys, it really works :)
