### ISSUE TITLE
Add Well-Known XML Extensions

### ISSUE THREAD

**Issue by DotJoshJohnson** [DotJoshJohnson/vscode-xml#196]
The following extensions should be supported by default:

```
.config
.csproj
.xml
.xsd
.xsl
```

**Comment by mrchief** [comment]
I would suggest to make it configurable (not sure if it already is). A lot of xml files do not end with x** extensions. E.g. `.csproj`, `web.config`, `.bpmn` and so on.

**Comment by DotJoshJohnson** [comment]
This is already configurable in your VS Code settings - this change will just add very common file extensions to the extension's configuration. `.csproj` and `.config` are definitely good additions to the list.

**Comment by DotJoshJohnson** [comment]
#232
