### ISSUE TITLE
Self Closing Tag Duplicates ">"

### ISSUE THREAD

**Issue by SharpSeeEr** [DotJoshJohnson/vscode-xml#199]
**Description**
When changing an existing, non-self closing element, `<firstname></firstname>`, to a self-closing type by removing the closing tag then adding a / in front of the opening tag's > a duplicate > is added.

```xml
<!-- initial setup -->
<firstname></firstname>
<!-- delete closing tag -->
<firstname>
<!-- add slash -->
<firstname/>
<!-- results in double gt -->
<firstname/>>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4459909/41479366-25cb0702-7088-11e8-915e-a8f387ca1398.png)

**Extension Version**
2.3.0

**VS Code Version**
![image](https://user-images.githubusercontent.com/4459909/41479421-52bca37e-7088-11e8-9c96-d060ed5baf6f.png)

**Operating System**
Windows 10 Professional Version 1803, OS build 17134.112

**Comment by DotJoshJohnson** [comment]
This extension doesn't provide "auto-close" functionality. Do you have another extension installed that does?

**Comment by SharpSeeEr** [comment]
I think I must have an extension that provides auto-close functionality.  :)  I'll figure that out and submit the bug there.  Thanks!
