### ISSUE TITLE
how to use evaluate xpath command?

### ISSUE THREAD

**Issue by spartawhy117** [DotJoshJohnson/vscode-xml#2]
what is the correct format when use evaluate xpath command?
like write`xml tool :evaluate xpath  XX\XXXX`?

**Comment by DotJoshJohnson** [comment]
@spartawhy117, I've added instructions for this feature to the [wiki here](https://github.com/DotJoshJohnson/vscode-xml/wiki/How-To:-Evaluate-XPath-Queries).
