### ISSUE TITLE
Format Selection Not Working

### ISSUE THREAD

**Issue by DotJoshJohnson** [DotJoshJohnson/vscode-xml#20]
When an XML fragment is selected and the `Format Code` command is issued, the selection is replaced with a formatted copy of the entire document. Only the selection should be formatted.

**Comment by philberesford** [comment]
I'm not sure if it's related, but I'm also seeing an error reported of: 
`No handler found for the command: 'xmlTools.formatXml'. Ensure there is an activation event defined, if you are...`

**Comment by DotJoshJohnson** [comment]
@philberesford This error typically pops up if something went wrong when activating the extension. When you open the XML file you are trying to format, do you see any errors pop up in the console? You can open the console under `Help` -> `Toggle Developer Tools` in VS Code.

**Comment by philberesford** [comment]
@DotJoshJohnson No sir. No other errors showing up (see attachment). After a bit more digging, it looks like Format Selection works correctly when operating on a file already saved to disk, but isn't working on a new, unsaved file (for me at least!).

![capture](https://cloud.githubusercontent.com/assets/3579449/12358782/cee5d586-bba6-11e5-928b-ebbb1aab644a.PNG)

**Comment by DotJoshJohnson** [comment]
@philberesford Ah, okay. The issue is that, until the language is set to "XML", the extension is never activated, which is when commands are attached to handlers. I'm not sure why VS Code is exposing commands before the extension is activated, but I'll certainly look into it. I'm sure it is something I'm missing in the manifest. I've created issue #23 to track this. Thanks for reporting it!

**Comment by philberesford** [comment]
You're more than welcome. Thanks for taking the time to write such a useful plugin!
