### ISSUE TITLE
Wrong formating of mixed content elements

### ISSUE THREAD

**Issue by tomassvoboda** [DotJoshJohnson/vscode-xml#200]
#### Description
White space is added to the content of mixed content element.
Formatting `<mixedContentNode>text<innerNode>innerNodeText</innerNode></mixedContentNode>` puts white space before the opening of the inner element.

#### Formatter Implementation
Using the default `xmlTools.xmlFormatterImplementation` setting value (`v2`).

#### XML Tools Version
2.3.1

#### VS Code Version
1.24.1

#### Operating System
Windows 10

**Comment by DotJoshJohnson** [comment]
I know this is technically valid XML, but I don't see it very often, so bear with me. What would the desired formatting be in this case?

**Option A**
```
<mixedContentNode>text
    <innerNode>innerNodeText</innerNode>
</mixedContentNode>
```

**Option B**
```
<mixedContentNode>
    text
    <innerNode>innerNodeText</innerNode>
</mixedContentNode>
```

**Comment by tomassvoboda** [comment]
I think using mixed content is a really bad practice and I don't think I have a good solution, but the only correct think to do in my opinion is to just not touch anything inside the `<mixedContentNode>`. That is obviously dumb think for a formatter to do, but I still have to see it as favourable to modifying the data of the XML by formatting it. Just like formatting simple `<node>text</node>` into
```
<node>
    text
</node>
```
would be modifying the data of the XML. I guess, I can see the formatting continuing inside the `inner` node like this:
```
<mixed>beginning text<inner>
    <a>data</a>
    <b>another data</b>
</inner>end text</mixed>
```

Other than that, I think Option A is better than Option B if only because it breaks the data a little less.

**Comment by tomassvoboda** [comment]
Please don't close this if it is not resolved.

**Comment by escobarOD** [comment]
WELL IM GLAD IS NOT O.D DOINGS

**Comment by escobarOD** [comment]
Hey thanks for the update I will be there shortly but I'm how u put it
shopping for the next producer of the OvErDoZed I'm giving up the chance to
do so to one of my beat Masters it help them Definitely and I'm going on
stage again and him too
