### ISSUE TITLE
Missing ) in xmlTools.xqueryExecutionArguments

### ISSUE THREAD

**Issue by tc-turner** [DotJoshJohnson/vscode-xml#207]
**Description**
The default settings for `xmlTools.xqueryExecutionArguments` are as follows

```json
  "xmlTools.xqueryExecutionArguments": [
    "-xquery",
    "$(script)",
    "-in",
    "$(input)",
    "-out",
    "$(input.output.xml"
  ],
```

The last line is missing a closing parenthesis, I updated my user settings to 

```json
    "xmlTools.xqueryExecutionArguments": [
        "-xquery",
        "$(script)",
        "-in",
        "$(input)",
        "-out",
        "$(input.output.xml)"
    ], 
```

And now I am able to use the xpath/xquery tools.

**Extension Version**
2.3.1

**VS Code Version**
1.24.1

**Operating System**
macOS 10.13.5

**Comment by silencesys** [comment]
I think based on the documentation and extension code it should be:

```json
    "xmlTools.xqueryExecutionArguments": [
        "-xquery",
        "$(script)",
        "-in",
        "$(input)",
        "-out",
        "$(input).output.xml"
    ], 
```

so it's only part of the filename replaced.
