### ISSUE TITLE
auto-close-tag.SublimeText3Mode not working?

### ISSUE THREAD

**Issue by MarcSharma** [DotJoshJohnson/vscode-xml#213]
**Description**
I have the following user settings:
```
    "auto-close-tag.SublimeText3Mode": true,
    "auto-close-tag.enableAutoCloseSelfClosingTag": false,
    "auto-close-tag.enableAutoCloseTag": false,
```
I expect that when I type `<foo>text</`, it autocompletes in `<foo>text</foo>`
I have also played with other close-tag setting to `false` and `true`, but nothing seems to work.

**Extension Version**
2.3.1

**VS Code Version**
1.25.1

**Operating System**
Mint

**Comment by DotJoshJohnson** [comment]
These settings are not contributed by the XML Tools extension. You have another extension installed providing those features.
