### ISSUE TITLE
VS Code there is no XML Tools: View XML Tree command

### ISSUE THREAD

**Issue by wenJanus** [DotJoshJohnson/vscode-xml#216]
#### Description
What seems to be the problem?
![image](https://user-images.githubusercontent.com/25690258/43951016-8c7075a6-9cc4-11e8-9ca1-b20b7d18dd2f.png)

#### Formatter Implementation
Which XML Formatter implementation are you using (the value of your `xmlTools.xmlFormatterImplementation` setting).

#### XML Tools Version
What version of XML Tools are you using?
![image](https://user-images.githubusercontent.com/25690258/43951090-c05e5590-9cc4-11e8-8ef0-68ed93c17c33.png)

#### VS Code Version
What version of VS Code are you using?
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
#### Operating System
What OS (and version) are you using?
Windows 7

**Comment by DotJoshJohnson** [comment]
This command was removed in version 1.9: https://github.com/DotJoshJohnson/vscode-xml/wiki/xml-tree-view.
