### ISSUE TITLE
`Get Current XPath` fail with error.

### ISSUE THREAD

**Issue by TEH30P** [DotJoshJohnson/vscode-xml#223]
**Description**
VSCode plugin fails with error when i try to get XPAth.

**Screenshots**
![Here you are.](https://user-images.githubusercontent.com/15148944/44327230-b11eb800-a466-11e8-9d55-434d0637dc09.gif)

**Extension Version**
2.3.2

**VS Code Version**
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Operating System**
OSName     : Microsoft Windows 10 Enterprise N
OSArc      : 64-bit
OSVersion  : 10.0.17134

**Comment by DotJoshJohnson** [comment]
The current XPath builder does not support anything other than attributes and elements. If the cursor is placed anywhere else, it fails. Adding support for text nodes should fix this issue.
