### ISSUE TITLE
XML Tree view displays single nodes for duplicate elements.

### ISSUE THREAD

**Issue by CarlLanglais** [DotJoshJohnson/vscode-xml#226]
**Description**
When reviewing an XML file that had the same element twice in a row, the XML tree displayed it as only having one element and when you clicked on a child element, it moved to the second instance of the element and ignored the first element.  Only the root element used the first instance.  Was reviewing a larger XML file than the example below and we wouldn't have noticed the duplication in the file that was causing our issue.

**Screenshots**
Screen shot should display NewDataSet twice and their corresponding child elements.
![image](https://user-images.githubusercontent.com/25389305/44856700-0cf1f980-ac3c-11e8-8719-26d6dd73e198.png)

**Extension Version**
1.9.2

**VS Code Version**
1.20.1

**Operating System**
Win 7

Example XML with the issue

`<NewDataSet>
    <BILL_DETAIL>
        <SEQ_NBR_ID>1</SEQ_NBR_ID>
        <CHG_EFF_DT>2018-02-09T00:00:00-05:00</CHG_EFF_DT>
        <ABS_BILL_METHOD xml:space="preserve"></ABS_BILL_METHOD>
        <ABS_DEP_RECV_IND xml:space="preserve"></ABS_DEP_RECV_IND>
        <ABS_CHECK_NBR xml:space="preserve"></ABS_CHECK_NBR>
        <ABS_CHECK_AMT>0.00</ABS_CHECK_AMT>
        <ABS_TYPE_PAY_CD xml:space="preserve"></ABS_TYPE_PAY_CD>
        <FK_SYSASSIGNNBRID>SAN123ABC</FK_SYSASSIGNNBRID>
        <PROC_TYPE_IND>A</PROC_TYPE_IND>
        <ABS_EFT_ONACT_IND xml:space="preserve"></ABS_EFT_ONACT_IND>
        <ABS_EFT_OFFACT_IND xml:space="preserve"></ABS_EFT_OFFACT_IND>
    </BILL_DETAIL>
    <BILL_INTEREST>
        <SEQ_NBR_ID>1</SEQ_NBR_ID>
        <ST_CD>XX</ST_CD>
        <CITY>Capital</CITY>
        <COUNTRY xml:space="preserve"></COUNTRY>
        <TYPE_CD>3</TYPE_CD>
        <ZIP_CD1>12345</ZIP_CD1>
        <ZIP_CD2>6789</ZIP_CD2>
        <ZIP_CD3 xml:space="preserve"></ZIP_CD3>
        <PHONE_AREA_CD>0</PHONE_AREA_CD>
        <PHONE_PREFIX_NBR>0</PHONE_PREFIX_NBR>
        <PHONE_SUFFIX_NBR>0</PHONE_SUFFIX_NBR>
        <CONTACT_NAME xml:space="preserve"></CONTACT_NAME>
        <STR_ADDR1>123 Main ST</STR_ADDR1>
        <STR_ADDR2 xml:space="preserve"></STR_ADDR2>
        <FK_SYSASSIGNNBRID>SAN123ABC</FK_SYSASSIGNNBRID>
        <FK_SEQ_NBR_ID>1</FK_SEQ_NBR_ID>
        <PROC_TYPE_IND>A</PROC_TYPE_IND>
        <CONTRACT_NBR>1234567</CONTRACT_NBR>
    </BILL_INTEREST>
    <BILL_INTEREST_NAME>
        <LINE_NBR_ID>1</LINE_NBR_ID>
        <NAME_TXT>The Name</NAME_TXT>
        <FK_SEQ_NBR_ID>1</FK_SEQ_NBR_ID>
        <FK_SYSASSIGNNBRID>SAN123ABC</FK_SYSASSIGNNBRID>
        <FK_SEQ_NBR_ID2>1</FK_SEQ_NBR_ID2>
        <PROC_TYPE_IND>A</PROC_TYPE_IND>
    </BILL_INTEREST_NAME>
</NewDataSet>
<NewDataSet>
    <BILL_DETAIL>
        <SEQ_NBR_ID>1</SEQ_NBR_ID>
        <CHG_EFF_DT>2018-02-09T00:00:00-05:00</CHG_EFF_DT>
        <ABS_BILL_METHOD xml:space="preserve"></ABS_BILL_METHOD>
        <ABS_DEP_RECV_IND xml:space="preserve"></ABS_DEP_RECV_IND>
        <ABS_CHECK_NBR xml:space="preserve"></ABS_CHECK_NBR>
        <ABS_CHECK_AMT>0.00</ABS_CHECK_AMT>
        <ABS_TYPE_PAY_CD xml:space="preserve"></ABS_TYPE_PAY_CD>
        <FK_SYSASSIGNNBRID>SAN123ABC</FK_SYSASSIGNNBRID>
        <PROC_TYPE_IND>A</PROC_TYPE_IND>
        <ABS_EFT_ONACT_IND xml:space="preserve"></ABS_EFT_ONACT_IND>
        <ABS_EFT_OFFACT_IND xml:space="preserve"></ABS_EFT_OFFACT_IND>
    </BILL_DETAIL>
    <BILL_INTEREST>
        <SEQ_NBR_ID>1</SEQ_NBR_ID>
        <ST_CD>XX</ST_CD>
        <CITY>Capital</CITY>
        <COUNTRY xml:space="preserve"></COUNTRY>
        <TYPE_CD>3</TYPE_CD>
        <ZIP_CD1>12345</ZIP_CD1>
        <ZIP_CD2>6789</ZIP_CD2>
        <ZIP_CD3 xml:space="preserve"></ZIP_CD3>
        <PHONE_AREA_CD>0</PHONE_AREA_CD>
        <PHONE_PREFIX_NBR>0</PHONE_PREFIX_NBR>
        <PHONE_SUFFIX_NBR>0</PHONE_SUFFIX_NBR>
        <CONTACT_NAME xml:space="preserve"></CONTACT_NAME>
        <STR_ADDR1>123 Main ST</STR_ADDR1>
        <STR_ADDR2 xml:space="preserve"></STR_ADDR2>
        <FK_SYSASSIGNNBRID>SAN123ABC</FK_SYSASSIGNNBRID>
        <FK_SEQ_NBR_ID>1</FK_SEQ_NBR_ID>
        <PROC_TYPE_IND>A</PROC_TYPE_IND>
        <CONTRACT_NBR>1234567</CONTRACT_NBR>
    </BILL_INTEREST>
    <BILL_INTEREST_NAME>
        <LINE_NBR_ID>1</LINE_NBR_ID>
        <NAME_TXT>The Name</NAME_TXT>
        <FK_SEQ_NBR_ID>1</FK_SEQ_NBR_ID>
        <FK_SYSASSIGNNBRID>SAN123ABC</FK_SYSASSIGNNBRID>
        <FK_SEQ_NBR_ID2>1</FK_SEQ_NBR_ID2>
        <PROC_TYPE_IND>A</PROC_TYPE_IND>
    </BILL_INTEREST_NAME>
</NewDataSet>`

**Comment by mackelito** [comment]
Just the kind of defect I was looking for 😄 
I need a way to filter out duplicates 😉

**Comment by DotJoshJohnson** [comment]
This behavior is caused by the tree view expecting a single root element in the XML document. For duplicate nodes *within* the document, the tree displays them (by default) with line number indicators to differentiate them:

![image](https://user-images.githubusercontent.com/8592596/50360248-6e144480-052d-11e9-8f11-d946df3ca720.png)

I don't currently plan on supporting XML documents with multiple root elements. I've generally taken the stance that I will only support standards-compliant documents. With that said, I will accept pull requests adding this feature if anyone wants to take that on.
