### ISSUE TITLE
Formatting Affects CDATA

### ISSUE THREAD

**Issue by emericklaw** [DotJoshJohnson/vscode-xml#227]
#### Description
From what I can see in the discussion in #5 CDATA formatting should be left alone.

However this does not seem to work.

```xml
<Job>
  <SQLQuery>
    <SQLSelect>
      <![CDATA[
        select
        *
        from test
        where
        aaa.aaa='AAA' and 
        isnull(BBB.BBB,0)=0 and
        isnull(CCC.CCC,0)=1 and
        DDD.DDD is null and
        exists (select 1 from EEE where EEE.EEE=EEE.EEE and EEE is null) and
        exists (select 1 from FFF where FFF.FFF=FFF.FFF) and
        '{GGG}' like '%'+GGG.GGG+'%'
      ]]>
    </SQLSelect>
	</SQLQuery>
</Job>
```

Becomes

```xml
<Job>
  <SQLQuery>
    <SQLSelect>
      <![CDATA[
        select
        *
        from test
        where aaa.aaa='AAA' and isnull(BBB.BBB,0)=0 and isnull(CCC.CCC,0)=1 and
        DDD.DDD is null and
        exists (select 1 from EEE where EEE.EEE=EEE.EEE and EEE is null) and
        exists (select 1 from FFF where FFF.FFF=FFF.FFF) and
        '{GGG}' like '%'+GGG.GGG+'%'
      ]]>
    </SQLSelect>
  </SQLQuery>
</Job>
```

I am not sure what it is trying to achieve since I would have thought more would be formatted onto one line.

#### Formatter Implementation
v2

#### XML Tools Version
2.3.2

#### VS Code Version
1.26.1

#### Operating System
Windows 10

**Comment by emericklaw** [comment]
After quickly learning how to develop/debug VSCode Extensions the offending code is:

https://github.com/DotJoshJohnson/vscode-xml/blob/84adff578f479ea976dde7faa6e983074e682da5/src/formatting/formatters/v2-xml-formatter.ts#L23-L25

**Comment by hossomi** [comment]
I've been having problems with this piece:
```xml
<![CDATA[

  SIP/2.0 200 OK
  [last_Via:]
  [last_From:]
  [last_To:];tag=[call_number]
  [last_Call-ID:]
  [last_CSeq:]
  Contact: <sip:[local_ip]:[local_port];transport=[transport]>
  Content-Type: application/sdp
  Content-Length: [len]
]]>
```
It's being formatted to:
```xml
<![CDATA[

  SIP/2.0 200 OK
  [last_Via:]
  [last_From:] [last_To:];tag=[call_number]
  [last_Call-ID:]
  [last_CSeq:]
  Contact: <sip:[local_ip]:[local_port];transport=[transport]>
  Content-Type: application/sdp
  Content-Length: [len]
]]>
```
This is my VSCode info:

Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:13:26.790Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-50-generic
