### ISSUE TITLE
can not see XQuery in command pallete

### ISSUE THREAD

**Issue by shengjun-zh** [DotJoshJohnson/vscode-xml#241]
I can not see XQuery related commands in command pallete. Even I set the required conditions as link below. Did I miss anything?
https://github.com/DotJoshJohnson/vscode-xml/wiki/xquery-script-execution

**Comment by DotJoshJohnson** [comment]
@shengjun-zh - This command only appears if you have an XQuery file open in the active editor (language mode set to "XQuery"). Can you confirm this is the case here?
