### ISSUE TITLE
What do you need to configure to enable XML Formatter?

### ISSUE THREAD

**Issue by kAlvaro** [DotJoshJohnson/vscode-xml#259]
#### Description
What seems to be the problem?

I've installed the extension and restarted Visual Studio Code several times, but when I launch the `Format Document` command (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd> in my system) it throws:

> There is no document formatter for 'xml'-files installed.

#### Formatter Implementation
Which XML Formatter implementation are you using (the value of your `xmlTools.xmlFormatterImplementation` setting).

`v2` (I haven't touched the default values). In fact that's the problem, I presume I need to configure something but the extension page doesn't mention it.

#### XML Tools Version
What version of XML Tools are you using?

2.4.0.

#### VS Code Version
What version of VS Code are you using?

1.30.2

#### Operating System
What OS (and version) are you using?

Windows 10 Pro (Spanish/Spain).

**Comment by nknganda** [comment]
Same issue.

**XML Tools Version**
2.4.0.

**VS Code Version**
1.33.1

**Operating System**
Ubuntu 18.04.2 LTS

**Comment by verschuur** [comment]
I have the same issue. Trying to format a large document (148Mb), nothing happens. All the XML Tools settings are default.

**XML Tools Version**
2.5.0

**Formatter Implementation**
v2

**VS Code Version**
1.34.0

**Operating System**
macOS Mojave / 10.14.5

**Update**
This also happens with the _XML Format_ extension, so maybe its something in vscode itself?

**Comment by nigelainscoe** [comment]
Same here, installed today. Trying to format a 270MB file.

VS Code 1.35.0, XML Tools 2.5.0 OS Mac
Same with XML Format extension.

**Update** - with the large file the right click menu shows only the XML minify option, with a small sample file (40KB) it also shows the format options, and they work.

**Comment by DotJoshJohnson** [comment]
I'll look into this deeper to confirm when I have time, but this is possibly related to issue #122.

**Comment by nigelainscoe** [comment]
Yes, it does look very like issue #122
<https://llink.to/?u=https:%2F%2Fgithub.com%2FDotJoshJohnson%2Fvscode-xml%2Fissues%2F122&e=4feb24c3e08ddd06ab7067d078f3c204>

Seeing this, I consider my  issue closed. It is not a massive deal to me at
the moment, just an inconvenience.

Thanks for your update.

Kind regards,
Nigel Ainscoe

**Comment by kAlvaro** [comment]
> I'll look into this deeper to confirm when I have time, but this is possibly related to issue #122.

So, if I understood correctly, you don't need to configure anything. Whatever problem I was having is a bug but it's probably related to large files, which was probably my case too. Then I think my issue is a duplicate of #122 indeed.
