### ISSUE TITLE
Every time I open an XML file I get the same notification.

### ISSUE THREAD

**Issue by leon-paul-hart** [DotJoshJohnson/vscode-xml#267]
I constantly get the notification : _"Heads up! We've rewritten the XML formatter. If you liked the old one better, it's still there. Just set the 'xmlTools.xmlFormatterImplementation' setting to 'classic'."_ which gets annoying very quickly when opening and closing Visual Studio code, as the message is shown every time the application starts and you open an xml file, there should be an option to dismiss the notificaton permanently.

**Comment by rsxdalv** [comment]
It's back at it...
