### ISSUE TITLE
Color formatting goes away for huge XML file

### ISSUE THREAD

**Issue by PascalFilion** [DotJoshJohnson/vscode-xml#281]
Issue Type: <b>Bug</b>

I have an XML file that is 12.4 MB, 318 328 lines. When I open the file, I see the color for the XML elements but within a second after the file is opened, the colors go away.

Extension version: 2.5.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.28GB free)|
|Process Argv|C:\Development\Active\active\Qbc.Active\Qbc.Active\packages.config|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joshuaavalon** [comment]
It is disabled by VS Code. You can force it by setting `editor.largeFileOptimizations` to `false`.
