### ISSUE TITLE
Installation faults with VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by bamiata** [DotJoshJohnson/vscode-xml#282]
When I try to install the latest version of XML Tools v2.5.0, on Windows 10, version 1809, for visual code version May 2019 (version 1.35) I get the following exception in the log file.

Any idea what might be wrong?

6/18/2019 9:12:15 PM - Microsoft VSIX Installer
6/18/2019 9:12:15 PM - -------------------------------------------
6/18/2019 9:12:15 PM - vsixinstaller.exe version:
6/18/2019 9:12:15 PM - 16.2.1045
6/18/2019 9:12:15 PM - -------------------------------------------
6/18/2019 9:12:15 PM - Command line parameters:
6/18/2019 9:12:15 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\UserName\Downloads\xml-2.5.0.vsix
6/18/2019 9:12:15 PM - -------------------------------------------
6/18/2019 9:12:15 PM - Microsoft VSIX Installer
6/18/2019 9:12:15 PM - -------------------------------------------
6/18/2019 9:12:15 PM - Initializing Install...
6/18/2019 9:12:15 PM - Extension Details...
6/18/2019 9:12:15 PM - 	Identifier         : xml
6/18/2019 9:12:15 PM - 	Name               : XML Tools
6/18/2019 9:12:15 PM - 	Author             : DotJoshJohnson
6/18/2019 9:12:15 PM - 	Version            : 2.5.0
6/18/2019 9:12:15 PM - 	Description        : XML Formatting, XQuery, and XPath Tools for Visual Studio Code
6/18/2019 9:12:15 PM - 	Locale             : en-US
6/18/2019 9:12:15 PM - 	MoreInfoURL        : 
6/18/2019 9:12:15 PM - 	InstalledByMSI     : False
6/18/2019 9:12:15 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/18/2019 9:12:15 PM - 
6/18/2019 9:12:15 PM - 	SignatureState     : Unsigned
6/18/2019 9:12:15 PM - 	Supported Products : 
6/18/2019 9:12:15 PM - 		Microsoft.VisualStudio.Code
6/18/2019 9:12:15 PM - 			Version : 
6/18/2019 9:12:15 PM - 
6/18/2019 9:12:15 PM - 	References         : 
6/18/2019 9:12:15 PM - Signature Details...
6/18/2019 9:12:15 PM - 	Extension is not signed.
6/18/2019 9:12:15 PM - 
6/18/2019 9:12:15 PM - Searching for applicable products...
6/18/2019 9:12:15 PM - Found installed product - Global Location
6/18/2019 9:12:15 PM - Found installed product - Visual Studio Professional 2017
6/18/2019 9:12:15 PM - Found installed product - Visual Studio Professional 2019
6/18/2019 9:12:15 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by nlsdg** [comment]
From the error log you provided you're trying to install in Visual Studio, not in Visual Studio Code.
Did you try to install the extension from within Visual Studio Code, or did you download the VSIX file and then double click it? The .VSIX file extension may be registered to Visual Studio, so it is trying to install it, but it is not designed for Visual Studio.

You can install a downloaded .VSIX file from within Visual Studio Code by opening the Extensions view, and clicking the three dots on the upper right corner. Then select Install from VSIX...
But using the Marketplace is probably easier.

**Comment by nlsdg** [comment]
Has the problem been solved? If so, please close it. If not, post a response and more relevant information.
