### ISSUE TITLE
add "get current xpath" to context menu.

### ISSUE THREAD

**Issue by DerekSMorin** [DotJoshJohnson/vscode-xml#284]
When right clicking to bring up context menu it would be nice if "Get Current XPath" showed up.

It looks like there is a command for this:

**XML Tools: Get Current XPath**

It was a little tricky to discover this feature, I was looking to see if a different extension would do it.

**Comment by LazaroOnline** [comment]
Same thing happened to me, I instinctively tried the right click context menu searching for this feature, then I checked the README.md and found nothing on this, until I came here to add a feature request and found this issue with the command solution.

Upvoted this issue and the request to add as a context menu option.
