### ISSUE TITLE
Can't collapse correctlly

### ISSUE THREAD

**Issue by royoan** [DotJoshJohnson/vscode-xml#290]
#### Description
What seems to be the problem?

if a xml file like this:
```
    <dependency >
      <fileName>httpclient-4.5.6.jar</fileName>
      <filePath>/BOOT-INF/lib/httpclient-4.5.6.jar</filePath>
      <md5>877aca56579fea38c6358d06408976ba</md5>
      <sha1>1afe5621985efe90a92d0fbc9be86271efbe796f</sha1>  
      <description>
   Apache HttpComponents Client
      </description>
   </dependency>
```
It can't collapse correctlly, show as below:

#### Formatter Implementation
Which XML Formatter implementation are you using (the value of your `xmlTools.xmlFormatterImplementation` setting).
v2

#### XML Tools Version
What version of XML Tools are you using?
v2.5.0
#### VS Code Version
What version of VS Code are you using?
1.39.2

#### Operating System
What OS (and version) are you using?
win10

**Comment by nils-a** [comment]
Hi, I'm guessing you meant  the collapsing of line 8 into line 7?

So, form
![image](https://user-images.githubusercontent.com/349188/82805977-311c5200-9e85-11ea-9668-702a60d798f6.png)
to
![image](https://user-images.githubusercontent.com/349188/82806018-472a1280-9e85-11ea-9a59-747606941265.png)

What you're seeing here is the default collapsing of vs-code - it depends on indentation of the content.

**Comment by DotJoshJohnson** [comment]
Indeed, this extension doesn’t provide the folding feature for XML - VS Code does that.
