### ISSUE TITLE
XML Formatter does not format document

### ISSUE THREAD

**Issue by weitzhandler** [DotJoshJohnson/vscode-xml#292]
**Description**
When working on a large XML file that doesn't contain line breaks, pressing <kbd>Ctrl</kbd>+ <kbd>Shift</kbd>+<kbd>I</kbd>, or launching the formatter from the command bar, does nothing.

The file is all condensed into one line. My expectation was that the formatter would insert line breaks after each node.

**Screenshots**
![image](https://user-images.githubusercontent.com/2716316/69537752-710f8480-0f89-11ea-9a97-5e8604ef60d4.png)

**Extension Version**
2.5.0

**VS Code Version**
1.40.1

**Operating System**
Windows 10 x64 - 1909

**Comment by DotJoshJohnson** [comment]
Can you attach a file that can be used to reproduce? Thanks!

**Comment by weitzhandler** [comment]
This issue is too old. I could have provided a repro closer to the date I opened it.
Hence I'll close it now.
