### ISSUE TITLE
Can't format local files when working remotely

### ISSUE THREAD

**Issue by t-schroeder** [DotJoshJohnson/vscode-xml#298]
**Description**
When I work locally with vscode the formatter works. When I work remotely it works as well (with the Remote SSH extension).

However, when I have a remote workspace open, then open a local XML file and try to format it I get "There is no formatter for 'xml' files installed."

**Extension Version**
2.5.0

**VS Code Version**
1.41.1

**Operating System**
Local: Windows 10
Remote: CentOS 7

**Comment by Morgy93** [comment]
Probably related to #283

**Comment by DotJoshJohnson** [comment]
This will be tracked in #283.
