### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by estjava** [DotJoshJohnson/vscode-xml#301]
[DotJoshJohnson.xml-unresponsive.cpuprofile.txt](https://github.com/DotJoshJohnson/vscode-xml/files/4160164/DotJoshJohnson.xml-unresponsive.cpuprofile.txt)
- Issue Type: `Bug`
- Extension Name: `xml`
- Extension Version: `2.5.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by nlsdg** [comment]
Please give this issue a descriptive title.
