### ISSUE TITLE
How to set catalog prefer as public in vscode setting?

### ISSUE THREAD

**Issue by mingxi** [DotJoshJohnson/vscode-xml#327]
**Description**
Is possible to set catalog prefer as public from vscode setting?
It seems that vscode-xml always set catalog as system id.
As far as I know, I can set catalog using CatalogManager.properties in java code.
I did not find the corresponding setting(prefer=public) in vscode-xml.
The below code is CatalogManager.properties which used to validate xml in java code.
e.g.
```
catalogs=C:\\DITA-OT\\catalog-dita.xml
relative-catalogs=yes
#verbosity=99
prefer=public
static-catalog=yes
allow-oasis-xml-catalog-pi=yes
```

**Comment by DotJoshJohnson** [comment]
It sounds like you are referring to a specific use case of XML that is outside the scope of XML Tools. XML Tools does not perform any sort of XSD validation or transformations. It only provides generic formatting, XPath evaluation, and XQuery execution (which itself is outsourced to the XQuery evaluator of your choice). I don't think I can help here.
