### ISSUE TITLE
Simply does not work at all

### ISSUE THREAD

**Issue by oliversalzburg** [DotJoshJohnson/vscode-xml#332]
#### Description
When trying to format a document, VS Code reports "There is no formatter for 'xml' files installed."

#### Formatter Implementation
I have not adjusted this. Setting it to any value has no effect.

#### XML Tools Version
2.5.1

#### VS Code Version
1.47.3

#### Operating System
Windows 10

**Comment by oliversalzburg** [comment]
Seems to be somehow related to WSL. The feature works as expected outside of WSL.

**Comment by achiang-dg** [comment]
Interesting, I've encountered the same issue. I have WSL 2 myself.

> the feature works as expected outside of WSL

What do you mean? Do you mean when not running VS Code with the [Remote - WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)?
If so, I tried VS Code with the Remote - WSL extension installed, uninstalled, and disabled, but still go the same no formatter error.

**Comment by oliversalzburg** [comment]
When I use the extension locally on the Windows side, it works as expected. Like when I just open a folder in VS Code from Explorer.

**Comment by DotJoshJohnson** [comment]
I'm closing this in favor of #283. This is planned, but I unfortunately have zero bandwidth right now for this extension. Once I get some free time on my hands, I'll continue working on this. Thanks!
