### ISSUE TITLE
Description Should tell that thios requires Java runtime!

### ISSUE THREAD

**Issue by alfnielsen** [DotJoshJohnson/vscode-xml#334]
So I downloaded this extension in the hope that it could format my xml files,
but vscode tell me that it can't find the Java-runtime!!
It is not described anywhere that this requires java.

**Comment by alfnielsen** [comment]
Well maybe im mistaken that is not this extension that run Java?
In that case the format simple dont due anything..

**Comment by angelozerr** [comment]
@alfnielsen you tried  [vscode-xml from Red Hat ](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) 
which required Java, but please install [vscode-xml 0.15.0 from Red Hat ](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) which **no longer require Java**.
