### ISSUE TITLE
Will not re-format large XML files

### ISSUE THREAD

**Issue by abergsneider** [DotJoshJohnson/vscode-xml#336]
**Description**
Attempting to format an XML document with over 62k lines of code. Take approximately 2 minutes to run with no changes afterward.

**Extension Version**
v2.5.1

**VS Code Version**
1.50.1

**Operating System**
Windows 10 Enterprise 2016 LTSB

**Comment by vyvuhoang** [comment]
I got same issue :(

**Comment by craigontour** [comment]
I have a 100MB file with 207K lines and it would not render. So I copied bit by bit to new file to help discover the 'problem', but there was nothing wrong. The new file rendered and showed View Tree, until I closed and re-opened. 
Using MacBook Pro, Big Sur 11.1.2 with 16GB RAM. Nothing else running.

**Comment by bmghirbi** [comment]
I have the same issue on Windows 10, vscode version 1.54.3

**Comment by craigontour** [comment]
To update, there were issues with the XML content. It included various fields that caused the rendering to fail.

**Comment by abergsneider** [comment]
Good morning all,
After some digging around I have changed one thing on the **settings.json** file of the extension and it seems to be doing the job for me now!

### Solution:
1. File/Preferences/Settings/XML/
2. Scroll down to XML>Sevrer: **Vmargs**
3. Click on "Edit in settings.json"
4. On `"xml.server.vmargs": ""` add **-Xmx1G** inside the brackets.
Make sure there are no trailing commas if this is your last _Key: Value_ inside the object.

Good luck!
