### ISSUE TITLE
XML Tools: Validate xPath only available via shortcut, not via VS Code menu

### ISSUE THREAD

**Issue by ameetmadan** [DotJoshJohnson/vscode-xml#340]
The option to validate xPath is only available via Ctrl+Shift+Alt+X instead of via the menu

**Comment by DotJoshJohnson** [comment]
Just to confirm, are you saying you want this command added to the right-click context menu? Or are you saying you can't find it in the command palette?

**Comment by ameetmadan** [comment]
![Snag_4c18b2f5](https://user-images.githubusercontent.com/39386429/100337147-537b5d80-2fd7-11eb-90a6-11e98bf885a4.png)
I was expecting to see the option here, but it wasn't there.

![Snag_4c19d07b](https://user-images.githubusercontent.com/39386429/100337308-7f96de80-2fd7-11eb-8477-3437d42e9a0d.png)
After using Ctrl + Shift + Alt + X on Windows I reached the xPath validation field to type in my xPath. I was wondering if it's possible to add the option to the main menu

**Comment by trustypelletgun** [comment]
I just installed this extension in VS Code 1.60.0 and I'm seeing the same behavior. @ameetmadan did you find a resolution for this?

**Comment by ameetmadan** [comment]
No, sadly not.

**Comment by nlsdg** [comment]
The option ('XML Tools: Evaluate XPath') is there. But it only appears when the language of the current file is set to XML.
(Definition for this is visible in [package.json](https://github.com/DotJoshJohnson/vscode-xml/blob/95702e6355fb35d77d2fea7da5af3f505df398a0/package.json#L228))
