### ISSUE TITLE
Improper formating

### ISSUE THREAD

**Issue by Lechus** [DotJoshJohnson/vscode-xml#46]
`<soapenv:Envelope 
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <s:Header 
        xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" />
    <soapenv:Body>
        <TableResponse 
            xmlns="http://xml.tools/">
            <TableResult>
                <TableLists>
                    <TableList>
                        <TableCode>Tool</TableCode>
                        <TableEntry>
                            <ElementCode>00001</ElementCode>
                            <ElementDescription>1</ElementDescription>
                        </TableEntry>
                        <TableEntry>
                            <ElementCode>0002</ElementCode>
                            <ElementDescription>2</ElementDescription>
                        </TableEntry>
                    </TableList>
                </TableLists>
            </TableResult>
        </TableResponse>
    </soapenv:Body>
</soapenv:Envelope>`

Shift+Alt+F format it, but... Body is intended as subchild of Header, should be on the same level.

**Comment by DotJoshJohnson** [comment]
This is happening because of the "attribute split" feature. A temporary workaround (assuming you don't need the attributes to be split) would be to [disable this feature in your settings file](https://github.com/TrueCommerce/vscode-xml/wiki/xml-formatting). The long-term fix will require some modifications to "ignore" attribute indentation levels.

**Comment by DotJoshJohnson** [comment]
This has been released in [v1.5.2](https://github.com/TrueCommerce/vscode-xml/releases/tag/v1.5.2). Thanks for reporting it!
