### ISSUE TITLE
Don't require an "xml" file extension

### ISSUE THREAD

**Issue by colonelchlorine** [DotJoshJohnson/vscode-xml#47]
Would be nice to just copy and paste some text into an "untitled" page and after selecting all (or portions) of text, simply doing a "Format" command (or alt-shift-f) to format the string with tabs/spaces. Tried this with a sample XML string and it doesn't work until I save that untitled file as a ".xml".

"Indent XML" is a similar Sublime plugin [https://github.com/alek-sys/sublimetext_indentxml](url) that works with selection.

**Comment by DotJoshJohnson** [comment]
You can do this by [setting the language to XML in the editor](http://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file) before performing the format command. This is a limitation of VS Code. We register our formatting provider with a language and VS Code loads the formatter once that language is "activated" by a document (by file extension or if the first line of the file is valid XML). By default, documents are opened as "Plain Text", so our formatting provider isn't loaded yet.

**Comment by colonelchlorine** [comment]
Thanks. Makes sense.
