### ISSUE TITLE
Improve XML Formatter

### ISSUE THREAD

**Issue by DotJoshJohnson** [DotJoshJohnson/vscode-xml#5]
The current XML formatter is a bit messy. It should be rewritten to include more edge cases to avoid messing with CDATA formatting and attribute contents.

Also, the current formatter will take elements that should normally appear like this: `<XmlElement></XmlElement>` and put a line break between the two tags. This shouldn't happen and should be corrected.

**Comment by DotJoshJohnson** [comment]
Bumping this to next milestone as I'm already behind due to the holidays.

**Comment by rdoubleui** [comment]
Should the formatter be self-written? Or is pulling in an external lib considerable? ~~What is this extension's license model, does it need to be specified?~~ So, external MIT licensend libs would be possible, right?

**Comment by DotJoshJohnson** [comment]
@rdoubleui The formatter can be an external library provided it allows for tab size configuration.

**Comment by DotJoshJohnson** [comment]
The formatter has been re-implemented in the vNext branch (eb43a46). This also resolves issue #11. The formatter code is based on the [`pretty-data` XML formatter](https://github.com/vkiryukhin/pretty-data/blob/master/pretty-data.js#L66), but cleaned up and rewritten as TypeScript.

**Comment by DotJoshJohnson** [comment]
PR #12
