### ISSUE TITLE
Extra newlines are added when user the Format Code command

### ISSUE THREAD

**Issue by jmiller101** [DotJoshJohnson/vscode-xml#54]
I've found a case in which an extra newline is added when `Format Code` is called:

Before:

``` xml
<?xml version="1.0"?>
<!-- TEST COMMENT -->
<text>
    <content />TEST_TEXT
</text>
```

After:

``` xml
<?xml version="1.0"?>
<!-- TEST COMMENT -->
<text>
    <content />TEST_TEXT

</text>
```

If I continue to do `Format Code` it will continue to add newlines after the `<content/>` line, like so:

``` xml
<?xml version="1.0"?>
<!-- TEST COMMENT -->
<text>
    <content />TEST_TEXT








</text>
```

I know this isn't necessarily a "best practice" when it comes to writing XML files, but it is still valid XML.

**Comment by jmiller101** [comment]
Just an update, for some reason if I remove `<!-- TEST COMMENT -->` then the formatter works fine.

So this will produce and extra line:

``` xml
<?xml version="1.0"?>
<!-- TEST COMMENT -->
<text>
    <content />TEST_TEXT
</text>
```

And this will not:

``` xml
<?xml version="1.0"?>
<text>
    <content />TEST_TEXT
</text>
```

**Comment by DotJoshJohnson** [comment]
Thanks for reporting, @jpariseau! The fix is available now in the [latest preview build](https://github.com/TrueCommerce/vscode-xml/releases/download/v1.6.0-preview.1/xml-1.6.0-preview.1.vsix). The extension should be updated in the marketplace before the end of May.
