### ISSUE TITLE
Format XSL files?

### ISSUE THREAD

**Issue by HansLanger** [DotJoshJohnson/vscode-xml#55]
How can add the function to "format code" to XSL and XSLT files?

**Comment by DotJoshJohnson** [comment]
Thanks for the contribution, @HansLanger! This feature is available now in the [latest preview build](https://github.com/TrueCommerce/vscode-xml/releases/download/v1.6.0-preview.1/xml-1.6.0-preview.1.vsix). The extension should be updated in the marketplace before the end of May.
