### ISSUE TITLE
Would like to contribute change to add optional 'insertSpaces' and 'tabSize' options to the formatter

### ISSUE THREAD

**Issue by AndyDragon** [DotJoshJohnson/vscode-xml#57]
I have a small change to the providers/Formatting.ts file to allow optional 'insertSpaces' and 'tabSize' options to the extension settings (defaults to build in values) to allow greater flexibility when formatting XML to allow different formatting than the defaults.

I would like to push a private branch for you to look over.

**Comment by DotJoshJohnson** [comment]
Sure thing! Feel free to open up a PR with the changes.
