### ISSUE TITLE
XPath / XQuery back-end for linux?

### ISSUE THREAD

**Issue by DawidLoubser** [DotJoshJohnson/vscode-xml#58]
Hi,

Has anybody successfully ran this extension on Linux? Which `xmlTools.xqueryExecutionEngine` works for you?

I'm thinking that **[Saxon](http://stackoverflow.com/a/8999664)** might be my best bet here, and am busy trying to formulate a working `xmlTools.xqueryExecutionArguments`, but a more detailed guide in terms of what this extension expects of such a tool (in terms of inputs / outputs) would be very useful.

**Comment by DotJoshJohnson** [comment]
I personally have not tested this extension on Linux. The build gets run on a Linux box before deployment in Travis CI, but that is about it. This extension was originally created for an internal team here at TrueCommerce, so it sees mostly Windows installs.

With that said, I have heard good things about [BaseX](http://basex.org/), which I believe is *NIX-compatible.

As far as the extension's interface, the executable of choice is just called as if it were being called from a command line/shell with the arguments you specify in [`xqueryExecutionArguments`](https://github.com/TrueCommerce/vscode-xml/wiki/xquery-script-execution). We aren't piping anything to `stdin` or doing any other fancy footwork there.

On the way back, we capture `stdout` and, if the process exits with a status other than "0", spit out the contents of `stdout` in an error notification. Generally, any error message you would normally see at the command line using your tool would be piped to the error notification. If the error message contains a line number (captured using this RegEx: `[Ll]ine:?\s*\d+`), a button is added to the error notification that will take you to the line in error.
