### ISSUE TITLE
xpath: count support

### ISSUE THREAD

**Issue by typekpb** [DotJoshJohnson/vscode-xml#64]
having xml:

```
<?xml version="1.0" encoding="UTF-8"?>

<bookstore>

<book>
  <title lang="en">Harry Potter</title>
  <price>29.99</price>
</book>

<book>
  <title lang="en">Learning XML</title>
  <price>39.95</price>
</book>

</bookstore> 
```

running XPath: `count(//book)`

Result:
- expected: `2`
- actual: `ERROR something went wrong while evaluating the XPath: Type error`

**Comment by DotJoshJohnson** [comment]
Thank you to @zawiasam for the contribution! This will be included in the next release.
