### ISSUE TITLE
[Re-Implement XML Tree View] - Navigate to Source Node on Double-Click

### ISSUE THREAD

**Issue by jawn** [DotJoshJohnson/vscode-xml#66]
Currently does not seem to do anything.

**Comment by wakeboarder3780** [comment]
Any chance we might see traction on this soon? The tree view would be very useful with it! Any way us interested users could help?

**Comment by DotJoshJohnson** [comment]
I'm currently struggling to find time to dedicate to this extension (I currently put about 1-2 hours per week into it if I can). I'm certainly open to accepting community contributions if anyone wants to take this on. But otherwise, I can't give you a solid timeline at the moment.

**Comment by jawn** [comment]
Thanks @DotJoshJohnson !
