### ISSUE TITLE
Displayed many XPath Results items in the dropdown list of the output window

### ISSUE THREAD

**Issue by fengyj** [DotJoshJohnson/vscode-xml#68]
every time I executed the xpath, an new XPath Results item will be added.

**Comment by DotJoshJohnson** [comment]
Hi @fengyj,

Could you provide an example of the XML and XPath query/queries you are using? When I tried to reproduce this using VS Code 1.8.1 and XML Tools 1.6.1, the output pane refreshed with each new query I executed.

Thanks!

**Comment by CN91** [comment]
I also experience this issue with VS code version 1.39.2 on windows 10 and XML tools 2.5.0 
Each query creates a new 'channel' in the output dropdown.

Using CTRL+shift+p and the xpath query runner.
