### ISSUE TITLE
It fails if the file is not saved to disk yet.

### ISSUE THREAD

**Issue by mattslay** [DotJoshJohnson/vscode-xml#69]
If you past in some XML, then select XML as the format (from the bottom right corner of VS), but you have not saved it to a disk file, it will fail.

**Comment by DotJoshJohnson** [comment]
Hi, @mattslay. Is this still an issue? I just tested this with VS Code 1.8.1 and XML Tools 1.6.1, and it worked fine. If you are still able to reproduce this, please let me know if you have any other XML-related extensions installed.

Thanks!

**Comment by adaugherity** [comment]
For me it works in general, however XML Tree view fails with an unsaved file:
>**Error** Unable to open '': Cannot read property 'getText' of undefined.
