### ISSUE TITLE
"Format code" seems to have stopped working?

### ISSUE THREAD

**Issue by pcolmer** [DotJoshJohnson/vscode-xml#70]
I'm opening an XML file in Visual Studio Code 1.5.2, right-clicking on the text, clicking on "Format code" and nothing is happening. XML Tools 1.6.0 is installed.

I'm not sure if a Code update has broken something so I can't be sure when this last worked.

Sorry for not being more helpful.

**Comment by trevordaniels** [comment]
This seems to have tanked for me recently as well, possibly since 1.5.0. Large files approx. 5000 lines take  20 seconds instead of 1 or 2 seconds. Files approx. 25000 lines hang vs code.

**Comment by DotJoshJohnson** [comment]
I honestly haven't had the time to revisit this extension over the past few months due to other priorities, so it is possible there have been some extension API changes I haven't kept up with. They are moving pretty fast over there! I'll take a look as soon as I can.

Thanks for reporting!

**Comment by Gil80** [comment]
Running into the same issue with large XML files.
"Format Code" doesn't work at all for large XML files. It doesn't hang VScode.
Short XML files can be formatted just fine.

**Comment by danechambers** [comment]
Running into same issue as @Gil80 . Using VS Code version 1.6.0 and XML Tools version 1.6.0

**Comment by maaron** [comment]
I played around with this a little, and it seems like there is some sort of performance regression in vscode  in how it applies TextEdit's.  The vscode-xml extension currently uses a single "replace" edit to indicate the formatting, but this seems to take vscode a very long time to apply, even though the editor remains responsive (makes it appear like it does nothing).

Replacing (no pun intended) the single "replace" edit with a "delete + insert" makes it perform a little better with the file I was testing with, but subsequent formats took much, much longer.  In my case, the initial file had few total lines, but they were extremely long.  After formatting, the file had a ton of short lines, so the line count seems to have a significant negative impact on the performance.  For me, this change made it usable enough for what I was doing, so I didn't investigate further.

Maybe vscode folks will wind up fixing the underlying performance issue?  I suspect it also affects other extensions and maybe even the editor itself...  Or maybe there is some other strategy for constructing the "edit list" that vscode tends to handle better?

**Comment by DotJoshJohnson** [comment]
Hi everyone! Can someone confirm if this is still an issue on the latest version of VS Code? If so, what operating system are you using? I am unable to reproduce the performance issue using the following:

* VS Code 1.8.1
* XML Tools 1.6.1
* Windows 10 (10.0.14393, x64)

Thanks!

EDIT: I also forgot to mention I used a file that is about 22,000+ lines formatted. The format completes in less than a second.

**Comment by trevordaniels** [comment]
Lightning quick again for me, 25,000 lines in less than a second.

XML Tools 1.6.1 alone was not enough, I needed VS Code 1.8.1

Thanks for fixing!

**Comment by DotJoshJohnson** [comment]
Good to hear! It must have been a regression on the VS Code side. No changes made here! Thanks for the help!

**Comment by sumeragigyou** [comment]
"Fomatting" doesn't work on the large XML file approx. 180,000+ lines.

- VS Code: 1.11.2
- XML Tools: 1.7.0
- Windows 10 (10.0.14393 x64)

Thanks!

**Comment by mdanetzky** [comment]
Doesn't work on 70MB single line xml.
- VS Code: 1.38.1
- XML Tools: 2.5.0
- Windows 10.0.18362
