### ISSUE TITLE
[Re-Implement XML Tree View] - Support Paths with Uppercase Characters on Linux

### ISSUE THREAD

**Issue by PomepuyN** [DotJoshJohnson/vscode-xml#71]
When trying to get the treeview on Ubuntu, if the path contains an uppercase char, it fails with this message:
`Impossible d'ouvrir '' : cannot open file:///home/nicolas/t%C3%A9l%C3%A9chargements/backup-1473699716781.xml. Detail: Fichier introuvable (/home/nicolas/téléchargements/backup-1473699716781.xml).`

The right path here is `home/nicolas/Téléchargements/backup-1473699716781.xml`

**Comment by heidricha** [comment]
confirm this. doesn't work even without localised letters, a single uppercase anywhere in the path ruins all.

**Comment by bruecke** [comment]
Same problem on Fedora linux.
