### ISSUE TITLE
web.config not valid after formatting.

### ISSUE THREAD

**Issue by janus007** [DotJoshJohnson/vscode-xml#74]
After a Format Code of web.config the xml is no longer valid.

**Comment by DotJoshJohnson** [comment]
Could you provide an example of the XML you are trying to format?

**Comment by psomasdaniel** [comment]
DotJosh,
I can provide mine. It minimized it to one line: 
<?xml version="1.0" encoding="UTF-8"?><configuration><system.webServer><staticContent><clientCache cacheControlMode="NoControl"/></staticContent></system.webServer><location path="app-03e4f9566e.js"><system.webServer><staticContent><clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00" /></staticContent></system.webServer></location></configuration><location path="vendor-d807c2f448.js"><system.webServer><staticContent><clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00" /></staticContent></system.webServer></location></configuration><location path="app-bcfbb51912.css"><system.webServer><staticContent><clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00" /></staticContent></system.webServer></location></configuration><location path="vendor-f09abfaf6d.css"><system.webServer><staticContent><clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00" /></staticContent></system.webServer></location></configuration>
